# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_edit_dialog_window(object):
    def setupUi(self, edit_dialog_window):
        edit_dialog_window.setObjectName("edit_dialog_window")
        edit_dialog_window.resize(676, 740)
        self.layoutWidget = QtWidgets.QWidget(edit_dialog_window)
        self.layoutWidget.setGeometry(QtCore.QRect(87, 14, 553, 437))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.airplane_type_ = QtWidgets.QSpinBox(self.layoutWidget)
        self.airplane_type_.setObjectName("airplane_type_")
        self.gridLayout.addWidget(self.airplane_type_, 0, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 0, 2, 1, 1)
        self.service_ceiling_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.service_ceiling_.setMaximum(50000.0)
        self.service_ceiling_.setObjectName("service_ceiling_")
        self.gridLayout.addWidget(self.service_ceiling_, 0, 3, 2, 1)
        self.radius_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.radius_.setMaximum(100000000.0)
        self.radius_.setSingleStep(1000.0)
        self.radius_.setObjectName("radius_")
        self.gridLayout.addWidget(self.radius_, 1, 1, 2, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 2, 2, 1, 1)
        self.max_take_off_weight_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.max_take_off_weight_.setMaximum(500000.0)
        self.max_take_off_weight_.setObjectName("max_take_off_weight_")
        self.gridLayout.addWidget(self.max_take_off_weight_, 2, 3, 2, 1)
        self.distance_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.distance_.setMaximum(100000000.0)
        self.distance_.setSingleStep(1000.0)
        self.distance_.setObjectName("distance_")
        self.gridLayout.addWidget(self.distance_, 3, 1, 2, 1)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 4, 2, 1, 1)
        self.empty_weight_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.empty_weight_.setMaximum(500000.0)
        self.empty_weight_.setObjectName("empty_weight_")
        self.gridLayout.addWidget(self.empty_weight_, 4, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.min_load_distance_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.min_load_distance_.setMaximum(100000000.0)
        self.min_load_distance_.setSingleStep(1000.0)
        self.min_load_distance_.setObjectName("min_load_distance_")
        self.gridLayout.addWidget(self.min_load_distance_, 5, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 5, 2, 1, 1)
        self.fuel_capacity_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.fuel_capacity_.setMaximum(500000.0)
        self.fuel_capacity_.setObjectName("fuel_capacity_")
        self.gridLayout.addWidget(self.fuel_capacity_, 5, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 6, 0, 1, 1)
        self.max_load_distance_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.max_load_distance_.setMaximum(100000000.0)
        self.max_load_distance_.setSingleStep(1000.0)
        self.max_load_distance_.setObjectName("max_load_distance_")
        self.gridLayout.addWidget(self.max_load_distance_, 6, 1, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 6, 2, 1, 1)
        self.max_load_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.max_load_.setMaximum(500000.0)
        self.max_load_.setObjectName("max_load_")
        self.gridLayout.addWidget(self.max_load_, 6, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 7, 0, 1, 1)
        self.flight_duration_time_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.flight_duration_time_.setMaximum(1000000.0)
        self.flight_duration_time_.setObjectName("flight_duration_time_")
        self.gridLayout.addWidget(self.flight_duration_time_, 7, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 2, 1, 1)
        self.engine_type_ = QtWidgets.QSpinBox(self.layoutWidget)
        self.engine_type_.setObjectName("engine_type_")
        self.gridLayout.addWidget(self.engine_type_, 7, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 8, 0, 1, 1)
        self.cruise_velocity_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.cruise_velocity_.setMaximum(10000000.0)
        self.cruise_velocity_.setObjectName("cruise_velocity_")
        self.gridLayout.addWidget(self.cruise_velocity_, 8, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 8, 2, 1, 1)
        self.engine_qty_ = QtWidgets.QSpinBox(self.layoutWidget)
        self.engine_qty_.setObjectName("engine_qty_")
        self.gridLayout.addWidget(self.engine_qty_, 8, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 9, 0, 1, 1)
        self.cruise_height_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.cruise_height_.setMaximum(50000.0)
        self.cruise_height_.setObjectName("cruise_height_")
        self.gridLayout.addWidget(self.cruise_height_, 9, 1, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 9, 2, 1, 1)
        self.engine_thrust_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.engine_thrust_.setMaximum(500000.0)
        self.engine_thrust_.setObjectName("engine_thrust_")
        self.gridLayout.addWidget(self.engine_thrust_, 9, 3, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 10, 0, 1, 1)
        self.min_velocity_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.min_velocity_.setMaximum(10000.0)
        self.min_velocity_.setObjectName("min_velocity_")
        self.gridLayout.addWidget(self.min_velocity_, 10, 1, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 10, 2, 1, 1)
        self.max_normal_overload_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.max_normal_overload_.setMaximum(100.0)
        self.max_normal_overload_.setObjectName("max_normal_overload_")
        self.gridLayout.addWidget(self.max_normal_overload_, 10, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 11, 0, 1, 1)
        self.max_roll_angle_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.max_roll_angle_.setMaximum(3.0)
        self.max_roll_angle_.setObjectName("max_roll_angle_")
        self.gridLayout.addWidget(self.max_roll_angle_, 11, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 11, 2, 1, 1)
        self.max_transverse_overload_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.max_transverse_overload_.setObjectName("max_transverse_overload_")
        self.gridLayout.addWidget(self.max_transverse_overload_, 11, 3, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 12, 0, 1, 1)
        self.max_on_height_velocity_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.max_on_height_velocity_.setMaximum(10000.0)
        self.max_on_height_velocity_.setObjectName("max_on_height_velocity_")
        self.gridLayout.addWidget(self.max_on_height_velocity_, 12, 1, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 12, 2, 1, 1)
        self.path_to_cdo_ = QtWidgets.QLineEdit(self.layoutWidget)
        self.path_to_cdo_.setText("")
        self.path_to_cdo_.setObjectName("path_to_cdo_")
        self.gridLayout.addWidget(self.path_to_cdo_, 12, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 13, 0, 1, 1)
        self.max_near_ground_velocity_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.max_near_ground_velocity_.setMaximum(10000.0)
        self.max_near_ground_velocity_.setObjectName("max_near_ground_velocity_")
        self.gridLayout.addWidget(self.max_near_ground_velocity_, 13, 1, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 13, 2, 1, 1)
        self.path_to_cdi_ = QtWidgets.QLineEdit(self.layoutWidget)
        self.path_to_cdi_.setText("")
        self.path_to_cdi_.setObjectName("path_to_cdi_")
        self.gridLayout.addWidget(self.path_to_cdi_, 13, 3, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 14, 0, 1, 1)
        self.patrol_velocity_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.patrol_velocity_.setMaximum(10000.0)
        self.patrol_velocity_.setObjectName("patrol_velocity_")
        self.gridLayout.addWidget(self.patrol_velocity_, 14, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget)
        self.label_27.setObjectName("label_27")
        self.gridLayout.addWidget(self.label_27, 14, 2, 1, 1)
        self.path_to_cl_ = QtWidgets.QLineEdit(self.layoutWidget)
        self.path_to_cl_.setText("")
        self.path_to_cl_.setObjectName("path_to_cl_")
        self.gridLayout.addWidget(self.path_to_cl_, 14, 3, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 15, 0, 1, 1)
        self.min_height_ = QtWidgets.QDoubleSpinBox(self.layoutWidget)
        self.min_height_.setMaximum(50000.0)
        self.min_height_.setObjectName("min_height_")
        self.gridLayout.addWidget(self.min_height_, 15, 1, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 15, 2, 1, 1)
        self.path_to_maximal_ = QtWidgets.QLineEdit(self.layoutWidget)
        self.path_to_maximal_.setText("")
        self.path_to_maximal_.setObjectName("path_to_maximal_")
        self.gridLayout.addWidget(self.path_to_maximal_, 15, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.save_changes_ = QtWidgets.QPushButton(edit_dialog_window)
        self.save_changes_.setGeometry(QtCore.QRect(340, 460, 201, 23))
        self.save_changes_.setObjectName("save_changes_")
        self.load_record_ = QtWidgets.QSpinBox(edit_dialog_window)
        self.load_record_.setGeometry(QtCore.QRect(180, 460, 47, 24))
        self.load_record_.setMinimum(-1)
        self.load_record_.setProperty("value", -1)
        self.load_record_.setObjectName("load_record_")
        self.label_29 = QtWidgets.QLabel(edit_dialog_window)
        self.label_29.setGeometry(QtCore.QRect(30, 460, 151, 16))
        self.label_29.setObjectName("label_29")

        self.retranslateUi(edit_dialog_window)
        self.service_ceiling_.valueChanged['double'].connect(edit_dialog_window.set_service_ceiling)
        self.max_take_off_weight_.valueChanged['double'].connect(edit_dialog_window.set_max_take_off_weight)
        self.empty_weight_.valueChanged['double'].connect(edit_dialog_window.set_empty_weight)
        self.fuel_capacity_.valueChanged['double'].connect(edit_dialog_window.set_fuel_capicity)
        self.max_load_.valueChanged['double'].connect(edit_dialog_window.set_max_load)
        self.engine_type_.valueChanged['int'].connect(edit_dialog_window.set_engine_type)
        self.engine_qty_.valueChanged['int'].connect(edit_dialog_window.set_engine_qty)
        self.engine_thrust_.valueChanged['double'].connect(edit_dialog_window.set_engine_thrust)
        self.max_normal_overload_.valueChanged['double'].connect(edit_dialog_window.set_max_normal_overload)
        self.max_transverse_overload_.valueChanged['double'].connect(edit_dialog_window.set_max_transverse_overload)
        self.path_to_cdo_.textChanged['QString'].connect(edit_dialog_window.set_path_to_cdo)
        self.path_to_cdi_.textChanged['QString'].connect(edit_dialog_window.set_path_to_cdi)
        self.path_to_cl_.textChanged['QString'].connect(edit_dialog_window.set_path_to_ci)
        self.path_to_maximal_.textChanged['QString'].connect(edit_dialog_window.set_path_to_maximal)
        self.airplane_type_.valueChanged['int'].connect(edit_dialog_window.set_airplane_type)
        self.radius_.valueChanged['double'].connect(edit_dialog_window.set_radius)
        self.distance_.valueChanged['double'].connect(edit_dialog_window.set_distance)
        self.min_load_distance_.valueChanged['double'].connect(edit_dialog_window.set_min_load_distance)
        self.max_load_distance_.valueChanged['double'].connect(edit_dialog_window.set_max_load_distance)
        self.flight_duration_time_.valueChanged['double'].connect(edit_dialog_window.set_flight_duration_time)
        self.cruise_velocity_.valueChanged['double'].connect(edit_dialog_window.set_cruise_velocity)
        self.cruise_height_.valueChanged['double'].connect(edit_dialog_window.set_cruise_velocity)
        self.min_velocity_.valueChanged['double'].connect(edit_dialog_window.set_min_velocity)
        self.max_roll_angle_.valueChanged['double'].connect(edit_dialog_window.set_max_roll_angle)
        self.max_on_height_velocity_.valueChanged['double'].connect(edit_dialog_window.set_max_on_height_velocity)
        self.max_near_ground_velocity_.valueChanged['double'].connect(edit_dialog_window.set_max_near_ground_velocity)
        self.patrol_velocity_.valueChanged['double'].connect(edit_dialog_window.set_patrol_velocity)
        self.min_height_.valueChanged['double'].connect(edit_dialog_window.set_min_height)
        self.save_changes_.clicked.connect(edit_dialog_window.save_changes)
        self.load_record_.valueChanged['int'].connect(edit_dialog_window.load_record)
        edit_dialog_window.airplane_type_set['int'].connect(self.airplane_type_.setValue)
        edit_dialog_window.radius_set['double'].connect(self.radius_.setValue)
        edit_dialog_window.distance_set['double'].connect(self.distance_.setValue)
        edit_dialog_window.min_load_distance_set['double'].connect(self.min_load_distance_.setValue)
        edit_dialog_window.max_load_distance_set['double'].connect(self.max_load_distance_.setValue)
        edit_dialog_window.flight_duration_time_set['double'].connect(self.flight_duration_time_.setValue)
        edit_dialog_window.cruise_velocity_set['double'].connect(self.cruise_velocity_.setValue)
        edit_dialog_window.cruise_height_set['double'].connect(self.cruise_height_.setValue)
        edit_dialog_window.min_velocity_set['double'].connect(self.min_velocity_.setValue)
        edit_dialog_window.max_roll_angle_set['double'].connect(self.max_roll_angle_.setValue)
        edit_dialog_window.max_on_height_velocity_set['double'].connect(self.max_on_height_velocity_.setValue)
        edit_dialog_window.max_near_ground_velocity_set['double'].connect(self.max_near_ground_velocity_.setValue)
        edit_dialog_window.patrol_velocity_set['double'].connect(self.patrol_velocity_.setValue)
        edit_dialog_window.min_height_set['double'].connect(self.min_height_.setValue)
        edit_dialog_window.service_ceiling_set['double'].connect(self.service_ceiling_.setValue)
        edit_dialog_window.max_take_off_weight_set['double'].connect(self.max_take_off_weight_.setValue)
        edit_dialog_window.empty_weight_set['double'].connect(self.empty_weight_.setValue)
        edit_dialog_window.fuel_capacity_set['double'].connect(self.fuel_capacity_.setValue)
        edit_dialog_window.max_load_set['double'].connect(self.max_load_.setValue)
        edit_dialog_window.engine_type_set['int'].connect(self.engine_type_.setValue)
        edit_dialog_window.engine_qty_set['int'].connect(self.engine_qty_.setValue)
        edit_dialog_window.engine_thrust_set['double'].connect(self.engine_thrust_.setValue)
        edit_dialog_window.max_normal_overload_set['double'].connect(self.max_normal_overload_.setValue)
        edit_dialog_window.max_transverse_overload_set['double'].connect(self.max_transverse_overload_.setValue)
        edit_dialog_window.path_to_cdi_set['QString'].connect(self.path_to_cdi_.setText)
        edit_dialog_window.path_to_cdo_set['QString'].connect(self.path_to_cdo_.setText)
        edit_dialog_window.path_to_maximal_set['QString'].connect(self.path_to_maximal_.setText)
        edit_dialog_window.path_to_cl_set['QString'].connect(self.path_to_cl_.setText)
        QtCore.QMetaObject.connectSlotsByName(edit_dialog_window)

    def retranslateUi(self, edit_dialog_window):
        _translate = QtCore.QCoreApplication.translate
        edit_dialog_window.setWindowTitle(_translate("edit_dialog_window", "Dialog"))
        self.label_15.setText(_translate("edit_dialog_window", "service_ceiling"))
        self.label_2.setText(_translate("edit_dialog_window", "radius"))
        self.label_16.setText(_translate("edit_dialog_window", "max_take_off_weight"))
        self.label_3.setText(_translate("edit_dialog_window", "distance"))
        self.label_17.setText(_translate("edit_dialog_window", "empty_weight "))
        self.label_4.setText(_translate("edit_dialog_window", "min_load_distance"))
        self.label_18.setText(_translate("edit_dialog_window", "fuel_capacity"))
        self.label_5.setText(_translate("edit_dialog_window", "max_load_distance"))
        self.label_19.setText(_translate("edit_dialog_window", "max_load "))
        self.label_6.setText(_translate("edit_dialog_window", "flight_duration_time"))
        self.label_20.setText(_translate("edit_dialog_window", "engine_type"))
        self.label_7.setText(_translate("edit_dialog_window", "cruise_velocity"))
        self.label_21.setText(_translate("edit_dialog_window", "engine_qty"))
        self.label_8.setText(_translate("edit_dialog_window", "cruise_height"))
        self.label_22.setText(_translate("edit_dialog_window", "engine_thrust"))
        self.label_9.setText(_translate("edit_dialog_window", "min_velocity"))
        self.label_23.setText(_translate("edit_dialog_window", "max_normal_overload"))
        self.label_10.setText(_translate("edit_dialog_window", "max_roll_angle"))
        self.label_24.setText(_translate("edit_dialog_window", "max_transverse_overload"))
        self.label_11.setText(_translate("edit_dialog_window", "max_on_height_velocity"))
        self.label_25.setText(_translate("edit_dialog_window", "path_to_cdo"))
        self.label_12.setText(_translate("edit_dialog_window", "max_near_ground_velocity"))
        self.label_26.setText(_translate("edit_dialog_window", "path_to_cdi"))
        self.label_13.setText(_translate("edit_dialog_window", "patrol_velocity "))
        self.label_27.setText(_translate("edit_dialog_window", "path_to_cl "))
        self.label_14.setText(_translate("edit_dialog_window", "min_height"))
        self.label_28.setText(_translate("edit_dialog_window", "path_to_maximal"))
        self.label.setText(_translate("edit_dialog_window", "airplane_type"))
        self.save_changes_.setText(_translate("edit_dialog_window", "Save changes"))
        self.label_29.setText(_translate("edit_dialog_window", "ID of record to configure"))

